#!/bin/bash

REPOSITORIES="
    servo/rust-url
    servo/rust-cssparser
    servo/rust-selectors
    servo/rust-quicksort
    servo/rust-smallvec
    servo/rust-fnv
    SimonSapin/rust-std-candidates
    SimonSapin/rust-wtf8
    SimonSapin/rust-casefold
    SimonSapin/rust-rctree
    SimonSapin/kuchiki
    serde-rs/aster
    serde-rs/serde
"

YELLOW=33
RED=31

function color {
    COLOR=$1
    shift
    echo -e "\033[1;${COLOR}m$@\033[0m"
}

FAILED=""

for REPOSITORY in $REPOSITORIES
do
    if [ -d clones/$REPOSITORY ]
    then
        (cd clones/$REPOSITORY && git fetch && git reset --hard origin/master)
    else
        git clone https://github.com/$REPOSITORY.git clones/$REPOSITORY
    fi

    if [ -f clones/$REPOSITORY/Makefile ]
    then
        color $YELLOW 'Running `make test` in' $REPOSITORY...
        make -C clones/$REPOSITORY test || FAILED="$FAILED $REPOSITORY"
    elif [ -f clones/$REPOSITORY/Cargo.toml ]
    then
        color $YELLOW 'Running `cargo test` in' $REPOSITORY...
        cargo test --manifest-path clones/$REPOSITORY/Cargo.toml || FAILED="$FAILED $REPOSITORY"
    elif [ -f clones/$REPOSITORY/*test*/Cargo.toml ]
    then
        color $YELLOW 'Running `cargo test` in' $REPOSITORY/*test*...
        cargo test --manifest-path clones/$REPOSITORY/*test*/Cargo.toml || FAILED="$FAILED $REPOSITORY"
    else
        color $RED 'Found neither `Makefile` not `Cargo.toml` in' $REPOSITORY
        RESULT=1
    fi
done

if [ -n "$FAILED" ]
then
    echo
    color $RED "Tests in some repositories have failed:$FAILED"
    exit 1
fi

